baseURL: "https://vvv.tobiassjosten.net"
locale: "en-us"
title: "Tobias Sjösten"

frontmatter:
  date:
    - date
    - :filename
    - :fileModTime
  lastmod:
    - lastmod
    - :fileModTime
    - date

summaryLength: 50

enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]
  term: ["HTML", "RSS"]

outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "feed"

menu:
  footer:
    - name: "Articles"
      url: "/articles/"
      weight: 1
    - name: "Books"
      url: "/books/"
      weight: 2
    - name: "Thinkers"
      url: "/thinkers/"
      weight: 3
    - name: "Projects"
      url: "/projects/"
      weight: 4
    - name: "Connect"
      url: "/connect/"
      weight: 5
    - name: "Using"
      url: "/uses/"
      weight: 6
    - name: "Now"
      url: "/now/"
      weight: 7

params:
  description: "An engineer and entrepreneur, with a passion for hacking systems; technical, social, and economic."
  author: "Tobias Sjösten"
  twitter: "tobiassjosten"
  image: "https://2.gravatar.com/avatar/04ce4aa9f079c590959ba7c47276549f?size=1200"
  show_recent_posts: 3
