baseURL: "https://vvv.tobiassjosten.net"
languageCode: "en-us"
title: "Tobias Sjösten"

frontmatter:
  date:
    - date
    - :filename
    - :fileModTime
  lastmod:
    - lastmod
    - :fileModTime
    - date

summaryLength: 50

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]
  term: ["HTML", "RSS"]

outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "feed"

menu:
  primary:
    - name: "About"
      url: "/about/"
      weight: 1
    - name: "Services"
      url: "/services/"
      weight: 2
    - name: "Connect"
      url: "/connect/"
      weight: 2

  secondary:
    - name: "Connect with me"
      url: "/connect/"
      weight: 1
    - name: "Articles"
      url: "/articles/"
      weight: 2
    - name: "Current focus"
      url: "/now/"
      weight: 3
    - name: "My toolbox"
      url: "/uses/"
      weight: 4
    - name: "Newsletter"
      url: "/newsletter/"
      weight: 5
    - name: "Resume"
      url: "/resume/"
      weight: 6
    - name: "Services"
      url: "/services/"
      weight: 7
    - name: "Speaking"
      url: "/speaking/"
      weight: 8
    - name: "Books"
      url: "/books/"
      weight: 9
    - name: "Businesses"
      url: "/businesses/"
      weight: 10

params:
  description: "Web technician and open source aficionado"
  author: "Tobias Sjösten"
  twitter: "tobiassjosten"
  ga_tracking_id: "UA-18939935-1"
  ga_tracking_id_secondary: "UA-18939935-2"
  domain: "vvv.tobiassjosten.net"
  show_recent_posts: 3
